# """
# Django settings for calendar_project project.

# Generated by 'django-admin startproject' using Django 4.2.4.

# For more information on this file, see
# https://docs.djangoproject.com/en/4.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/4.2/ref/settings/
# """

# from datetime import timedelta
# import os
# from pathlib import Path
# # from dotenv import load_dotenv
# import environ

# # # Load environment variables from .env file
# # load_dotenv()

# #ENVIROMENT VARIABLES
# env = environ.Env()
# environ.Env.read_env()

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# # FRONTEND_DIR = os.path.join(BASE_DIR, 'React/react_login/build')

# # STATICFILES_DIRS = [
# #     FRONTEND_DIR,
# # ]

# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-+wd!2rqsqg151g15m1v^9fu4)0&ol6qt_wg=z_7pkwqeav8nmh'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# #####################
# # DEBUG = False

# ALLOWED_HOSTS = ['*']
# # ALLOWED_HOSTS = ['localhost']
# # ALLOWED_HOSTS = ['ALL']

# # Application definition

# # INSTALLED_APPS = [
# #     'django.contrib.admin',
# #     'django.contrib.auth',
# #     'django.contrib.contenttypes',
# #     'django.contrib.sessions',
# #     'django.contrib.messages',
# #     'django.contrib.staticfiles',
# #     'api_calendar',
# #     'rest_framework',
# #     'corsheaders',
# #     'dj_rest_auth',
# #     'rest_framework.authtoken'
# # #   'dj_rest_auth.registration',

# #     # If using JWT tokens
# #     # 'rest_framework_simplejwt.token_blacklist',
# # ]

# ##############################################################################


# REST_FRAMEWORK = {
#     "DEFAULT_AUTHENTICATION_CLASSES": [
#         "rest_framework.authentication.TokenAuthentication",
#     ]
# }


# LOGIN_REDIRECT_URL = '/'

# INSTALLED_APPS = (
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'api_calendar',
#     'rest_framework',
#     'corsheaders',
#     'dj_rest_auth',
#     'rest_framework.authtoken',
#     'authentication',
#     'rest_framework_simplejwt.token_blacklist',
#     "allauth",
#     "allauth.account",
#     "allauth.socialaccount",
#     'django.contrib.sites',
#     'dj_rest_auth.registration',
#     'phonenumber_field',
#     'django_filters'
# )

# SITE_ID = 1


# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',
# ]

# # ///////////////////////////////////

# MIDDLEWARE = [
#     'allauth.account.middleware.AccountMiddleware',
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'corsheaders.middleware.CorsMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'calendar_project.urls'


# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         # 'DIRS': [],
#         'DIRS': [BASE_DIR / 'templates'],  # Add your templates directory here.
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'calendar_project.wsgi.application'

# # Database
# # https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': os.getenv('DB_NAME'),
# #         'USER': os.getenv('DB_USER'),
# #         'PASSWORD': os.getenv('DB_PASSWORD'),
# #         'HOST': os.getenv('DB_HOST'),
# #         'PORT': os.getenv('DB_PORT'),
# #     }
# # }

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# REST_FRAMEWORK = {
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.AllowAny',
#         'rest_framework.permissions.IsAuthenticated',
#     ),
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     )
# }
# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
#     'ROTATE_REFRESH_TOKENS': True,
#     'BLACKLIST_AFTER_ROTATION': False,
#     'ALGORITHM': 'HS256',
#     'SIGNING_KEY': SECRET_KEY,
#     'VERIFYING_KEY': None,
#     'AUTH_HEADER_TYPES': ('JWT',),
#     'USER_ID_FIELD': 'id',
#     'USER_ID_CLAIM': 'user_id',
#     'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
#     'TOKEN_TYPE_CLAIM': 'token_type',
# }

# # Password validation
# # https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

# # Internationalizationf
# # https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True

# CORS_ALLOW_ALL_ORIGINS = True
# # CORS_ORIGIN_WHITELIST = (
# #     'http://localhost:3000',  # for localhost (REACT Default)
# #     'http://192.168.0.50:3000',  # for network
# #     'http://localhost:8000',  # for localhost (Developlemt)
# #     'http://192.168.0.50:8080',  # for network (Development)
# # )
# # CORS_ALLOWED_ORIGINS = [
# #     'http://localhost:8000',
# # ]
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = '/static/'

# AUTH_USER_MODEL = 'authentication.CustomUser'
# # Default primary key field type
# # https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST          = env('EMAIL_HOST')
# EMAIL_PORT          = env('EMAIL_PORT')
# EMAIL_HOST_USER     = env('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
# EMAIL_USE_TLS       = True
# EMAIL_USE_SSL       = False

# SMS_API_KEY = env('SMS_API_KEY')

# RESET_URL = env('RESET_URL')

"""
Django settings for calendar_project project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see

https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path

# from dotenv import load_dotenv
import environ

# # Load environment variables from .env file
# load_dotenv()

# ENVIROMENT VARIABLES
env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# FRONTEND_DIR = os.path.join(BASE_DIR, 'React/react_login/build')

# STATICFILES_DIRS = [
#     FRONTEND_DIR,
# ]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-+wd!2rqsqg151g15m1v^9fu4)0&ol6qt_wg=z_7pkwqeav8nmh"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
#####################
DEBUG = True

ALLOWED_HOSTS = ["*"]
# ALLOWED_HOSTS = ['localhost']
# ALLOWED_HOSTS = ['ALL']

# Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'api_calendar',
#     'rest_framework',
#     'corsheaders',
#     'dj_rest_auth',
#     'rest_framework.authtoken'
# #   'dj_rest_auth.registration',

#     # If using JWT tokens
#     # 'rest_framework_simplejwt.token_blacklist',
# ]

##############################################################################


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ]
}


LOGIN_REDIRECT_URL = "/"

INSTALLED_APPS = (
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "api_calendar",
    "rest_framework",
    "corsheaders",
    "dj_rest_auth",
    "rest_framework.authtoken",
    "authentication",
    "rest_framework_simplejwt.token_blacklist",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "django.contrib.sites",
    "dj_rest_auth.registration",
    "phonenumber_field",
    "django_filters",
)

SITE_ID = 1


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

# ///////////////////////////////////

MIDDLEWARE = [
    "allauth.account.middleware.AccountMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "calendar_project.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # 'DIRS': [],
        "DIRS": [BASE_DIR / "templates"],  # Add your templates directory here.
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "calendar_project.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME'),
#         'USER': os.getenv('DB_USER'),
#         'PASSWORD': os.getenv('DB_PASSWORD'),
#         'HOST': os.getenv('DB_HOST'),
#         'PORT': os.getenv('DB_PORT'),
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("JWT",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalizationf
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

CORS_ALLOW_ALL_ORIGINS = True
# CORS_ORIGIN_WHITELIST = (
#     'http://localhost:3000',  # for localhost (REACT Default)
#     'http://192.168.0.50:3000',  # for network
#     'http://localhost:8000',  # for localhost (Developlemt)
#     'http://192.168.0.50:8080',  # for network (Development)
# )
# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:8000',
# ]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"

AUTH_USER_MODEL = "authentication.CustomUser"
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env("EMAIL_PORT")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

SMS_API_KEY = env("SMS_API_KEY")

RESET_URL = env("RESET_URL")

CSRF_TRUSTED_ORIGINS = [
    "https://economidesbackend.ti-talostech.info",
    "https://economides.ti-talostech.info",
]

CORS_ALLOWED_ORIGINS = [
    "https://economidesbackend.ti-talostech.info",
    "https://economides.ti-talostech.info",
]
